### PR TITLE
[camera_web] Remove invalid @JS annotation on extension type constructors

### LINKED ISSUE #190355: Packages roller blocked on JS interop errors
The flutter/flutter -> flutter/packages roller is currently blocked on JS interop errors. I've bisected it down to https://github.com/flutter/packages/pull/12328 which is [this Dart roll](https://github.com/flutter/flutter/pull/190158). I'm not familiar enough with the internals of JS interop to know what the solution is here to unblock the roller.

```
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../packages/camera/camera_web/lib/src/pkg_web_tweaks.dart:47:20:
Error: The '@JS' annotation on an extension type constructor has no effect.
  external factory WebTweakMediaSettingsRange({num max, num min, num step});
                   ^
../packages/camera/camera_web/lib/src/pkg_web_tweaks.dart:67:20:
Error: The '@JS' annotation on an extension type constructor has no effect.
  external factory WebTweakMediaTrackConstraints({JSAny zoom, ConstrainBoolean torch});
                   ^
Error: Compilation failed.
```

As usual with flutter/packages, if at all possible we want a solution that is compatible with both `stable` and `master`.

### PR DESCRIPTION
**Pull request by mdebbar**
Removes invalid `@JS()` annotations from extension type constructors in `packages/camera/camera_web`.

Fixes https://github.com/flutter/flutter/issues/190355

### Description
In newer Dart SDKs (following Dart SDK commit https://github.com/dart-lang/sdk/commit/cecd7ec2585f8330522c73c0c867c01a867532e5 rolled into Flutter in PR https://github.com/flutter/flutter/pull/190158), placing `@JS()` annotations on extension type constructors has no effect and is now flagged as an error (`invalid_js_annotation`).

Removing these annotations resolves the error without altering runtime behavior.

### CODE REVIEW

**Comment by mdebbar** [comment]
Not sure what's wrong with `GitHub Actions Scan`. Any idea @stuartmorgan-g ?

**Comment by stuartmorgan-g** [comment]
No clue I'm afraid; I don't know anything about the infrastructure for the new zizmor scans.

(I triggered a re-run to see if that helps, since it looked like some internal server issue.)

**Review by stuartmorgan-g — APPROVED** [review]
LGTM

**Comment by mdebbar** [comment]
Github is having issues (https://www.githubstatus.com/)
image
